-- 创建库
create database yu_picture;


CREATE TABLE IF NOT EXISTS "user" (
    id           BIGSERIAL PRIMARY KEY,
    "userAccount"  VARCHAR(256) NOT NULL,
    "userPassword" VARCHAR(512) NOT NULL,
    "userName"     VARCHAR(256),
    "userAvatar"   VARCHAR(1024),
    "userProfile"  VARCHAR(512),
    "userRole"     VARCHAR(256) NOT NULL DEFAULT 'user',
    "editTime"     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createTime"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDelete"     SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_userAccount UNIQUE ("userAccount")
);
-- 创建索引
CREATE INDEX IF NOT EXISTS idx_userName ON "user" ("userName");

-- 添加表注释
COMMENT ON TABLE "user" IS '用户';

-- 添加列注释
COMMENT ON COLUMN "user".id IS 'id';
COMMENT ON COLUMN "user"."userAccount" IS '账号';
COMMENT ON COLUMN "user"."userPassword" IS '密码';
COMMENT ON COLUMN "user"."userName" IS '用户昵称';
COMMENT ON COLUMN "user"."userAvatar" IS '用户头像';
COMMENT ON COLUMN "user"."userProfile" IS '用户简介';
COMMENT ON COLUMN "user"."userRole" IS '用户角色：user/admin';
COMMENT ON COLUMN "user"."editTime" IS '编辑时间';
COMMENT ON COLUMN "user"."createTime" IS '创建时间';
COMMENT ON COLUMN "user"."updateTime" IS '更新时间';
COMMENT ON COLUMN "user"."isDelete" IS '是否删除';

-- 图片表
CREATE TABLE IF NOT EXISTS picture (
                                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       url          VARCHAR(512) NOT NULL,
    name         VARCHAR(128) NOT NULL,
    introduction VARCHAR(512),
    category     VARCHAR(64),
    tags         VARCHAR(512),
    "picSize"      BIGINT,
    "picWidth"     INTEGER,
    "picHeight"    INTEGER,
    "picScale"     DOUBLE PRECISION,
    "picFormat"    VARCHAR(32),
    "userId"       BIGINT NOT NULL,
    "createTime"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "editTime"     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updateTime"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isDelete"     SMALLINT DEFAULT 0 NOT NULL
    );

-- 索引
CREATE INDEX idx_name ON picture (name);
CREATE INDEX idx_introduction ON picture (introduction);
CREATE INDEX idx_category ON picture (category);
CREATE INDEX idx_tags ON picture (tags);
CREATE INDEX idx_userId ON picture ("userId");

-- 字段注释
COMMENT ON TABLE picture IS '图片';
COMMENT ON COLUMN picture.id IS 'id';
COMMENT ON COLUMN picture.url IS '图片 url';
COMMENT ON COLUMN picture.name IS '图片名称';
COMMENT ON COLUMN picture.introduction IS '简介';
COMMENT ON COLUMN picture.category IS '分类';
COMMENT ON COLUMN picture.tags IS '标签（JSON 数组）';
COMMENT ON COLUMN picture."picSize" IS '图片体积';
COMMENT ON COLUMN picture."picWidth" IS '图片宽度';
COMMENT ON COLUMN picture."picHeight" IS '图片高度';
COMMENT ON COLUMN picture."picScale" IS '图片宽高比例';
COMMENT ON COLUMN picture."picFormat" IS '图片格式';
COMMENT ON COLUMN picture."userId" IS '创建用户 id';
COMMENT ON COLUMN picture."createTime" IS '创建时间';
COMMENT ON COLUMN picture."editTime" IS '编辑时间';
COMMENT ON COLUMN picture."updateTime" IS '更新时间';
COMMENT ON COLUMN picture."isDelete" IS '是否删除';


ALTER TABLE picture
    ADD COLUMN "reviewStatus" INT NOT NULL DEFAULT 0,
    ADD COLUMN "reviewMessage" VARCHAR(512),
    ADD COLUMN "reviewerId" BIGINT,
    ADD COLUMN "reviewTime" TIMESTAMP;

COMMENT ON COLUMN picture."reviewStatus" IS '审核状态：0-待审核; 1-通过; 2-拒绝';
COMMENT ON COLUMN picture."reviewMessage" IS '审核信息';
COMMENT ON COLUMN picture."reviewerId" IS '审核人 ID';
COMMENT ON COLUMN picture."reviewTime" IS '审核时间';


-- 创建基于 reviewStatus 列的索引
CREATE INDEX idx_reviewStatus ON picture ("reviewStatus");

ALTER TABLE picture
    -- 添加新列
    ADD COLUMN thumbnailUrl varchar(512) NULL COMMENT '缩略图 url';


-- 空间表
create table if not exists space
(
    id         bigint auto_increment comment 'id' primary key,
    spaceName  varchar(128)                       null comment '空间名称',
    spaceLevel int      default 0                 null comment '空间级别：0-普通版 1-专业版 2-旗舰版',
    maxSize    bigint   default 0                 null comment '空间图片的最大总大小',
    maxCount   bigint   default 0                 null comment '空间图片的最大数量',
    totalSize  bigint   default 0                 null comment '当前空间下图片的总大小',
    totalCount bigint   default 0                 null comment '当前空间下的图片数量',
    userId     bigint                             not null comment '创建用户 id',
    createTime datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    editTime   datetime default CURRENT_TIMESTAMP not null comment '编辑时间',
    updateTime datetime default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    isDelete   tinyint  default 0                 not null comment '是否删除',
    -- 索引设计
    index idx_userId (userId),        -- 提升基于用户的查询效率
    index idx_spaceName (spaceName),  -- 提升基于空间名称的查询效率
    index idx_spaceLevel (spaceLevel) -- 提升按空间级别查询的效率
) comment '空间' collate = utf8mb4_unicode_ci;

-- 添加新列
ALTER TABLE picture
    ADD COLUMN spaceId bigint  null comment '空间 id（为空表示公共空间）';

-- 创建索引
CREATE INDEX idx_spaceId ON picture (spaceId);

-- 添加新列
ALTER TABLE picture
    ADD COLUMN picColor varchar(16) null comment '图片主色调';

-- 支持空间类型，添加新列
ALTER TABLE space
    ADD COLUMN spaceType int default 0 not null comment '空间类型：0-私有 1-团队';

CREATE INDEX idx_spaceType ON space (spaceType);

-- 空间成员表
create table if not exists space_user
(
    id         bigint auto_increment comment 'id' primary key,
    spaceId    bigint                                 not null comment '空间 id',
    userId     bigint                                 not null comment '用户 id',
    spaceRole  varchar(128) default 'viewer'          null comment '空间角色：viewer/editor/admin',
    createTime datetime     default CURRENT_TIMESTAMP not null comment '创建时间',
    updateTime datetime     default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    -- 索引设计
    UNIQUE KEY uk_spaceId_userId (spaceId, userId), -- 唯一索引，用户在一个空间中只能有一个角色
    INDEX idx_spaceId (spaceId),                    -- 提升按空间查询的性能
    INDEX idx_userId (userId)                       -- 提升按用户查询的性能
) comment '空间用户关联' collate = utf8mb4_unicode_ci;

-- 扩展用户表：新增会员功能
ALTER TABLE user
    ADD COLUMN vipExpireTime datetime NULL COMMENT '会员过期时间',
    ADD COLUMN vipCode varchar(128) NULL COMMENT '会员兑换码',
    ADD COLUMN vipNumber bigint NULL COMMENT '会员编号';
